# Generated by Django 6.0.4 on 2026-04-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pedido_finalizado_pedido_nome_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
